### ISSUE TITLE
super function call with spread argument

### ISSUE THREAD

**Issue by kzc** [TimMensch/buble#1]
Looks like [most of the patches were merged](https://gitlab.com/Rich-Harris/buble/blob/master/CHANGELOG.md) at buble's gitlab home and released except for this rather significant one:

super function call with spread argument
https://gitlab.com/Rich-Harris/buble/merge_requests/89

**Comment by TimMensch** [comment]
OK, I've grabbed that one too, and I merged all into TimMensch/buble (master), so you should be able to `npm install TimMensch/buble`. Or run `npm upgrade` if you're already on master.

**Comment by kzc** [comment]
Good stuff!
